# Site settings
title:        figtree
email:        hello@figtree-digital.com
author:       Natasha Vlahakis
description:  "A Digital Agency based in Barbados."
baseurl:      "http://natashavlahakis.github.io/figtree"
url:          "http://natashavlahakis.github.io/figtree"
behance:      figtreedigital
linkedin:     figtreedigital
twitter:      figtreedigital