# Site settings
title:        figtree
email:        hello@figtree-studio.com
author:       Natasha Vlahakis
description:  "A Digital Agency based in Barbados."
baseurl:      "http://figtree-studio.com"
url:          "http://figtree-studio.com"
behance:      figtreestudio
linkedin:     figtreestudio
twitter:      figtreestudio