# Site settings
title:        figtree
email:        hello@figtree-digital.com
author:       Natasha Vlahakis
description:  "A Digital Agency based in Barbados."
baseurl:      "http://figtree-digital.com"
url:          "http://figtree-digital.com"
behance:      figtreedigital
linkedin:     figtreedigital
twitter:      figtreedigital